.PHONY: clean All

All:
	@echo "----------Building project:[ ref_test - Debug ]----------"
	@cd "C:\Dev\HCommitCa\ref_test" && "$(MAKE)" -f  "ref_test.mk"
clean:
	@echo "----------Cleaning project:[ ref_test - Debug ]----------"
	@cd "C:\Dev\HCommitCa\ref_test" && "$(MAKE)" -f  "ref_test.mk" clean
