.PHONY: clean All

All:
	@echo "----------Building project:[ HCommitCa - Debug ]----------"
	@"$(MAKE)" -f  "HCommitCa.mk" && "$(MAKE)" -f  "HCommitCa.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ HCommitCa - Debug ]----------"
	@"$(MAKE)" -f  "HCommitCa.mk" clean
