.PHONY: clean All

All:
	@echo "----------Building project:[ HCommitCa - Debug ]----------"
	@"$(MAKE)" -f  "HCommitCa.mk"
clean:
	@echo "----------Cleaning project:[ HCommitCa - Debug ]----------"
	@"$(MAKE)" -f  "HCommitCa.mk" clean
